# Generated by Django 3.0.7 on 2020-06-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='address',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='email',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
