# Generated by Django 3.0.7 on 2020-06-18 21:26

from django.db import migrations, models
import restApi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_auto_20200618_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='image',
            field=models.FileField(null=True, upload_to='photos', validators=[restApi.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='image',
            field=models.FileField(null=True, upload_to='photos', validators=[restApi.validators.validate_image_file_extension]),
        ),
    ]
