# Generated by Django 3.0.7 on 2020-06-03 21:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('password_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=45)),
                ('surname', models.CharField(default='', max_length=45)),
                ('mail', models.CharField(default='', max_length=45)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('password_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.Password')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permissions_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApi.User')),
            ],
        ),
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('job_adv_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('expiration_date', models.DateTimeField(verbose_name='expiration date')),
                ('salary', models.FloatField()),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApi.EmployerProfile')),
                ('tags', models.ManyToManyField(to='restApi.Tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApi.User')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApi.User')),
            ],
        ),
    ]
